export const ROUTE_CHANGED = 'router/ROUTE_CHANGED'

// Common
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_STATUS = 'UPDATE_STATUS'

// PariMutuel
export const UPDATE_TOTAL_WAGERED = 'UPDATE_TOTAL_WAGERED'
export const UPDATE_TOTAL_WAGERED_FOR_OUTCOMES = 'UPDATE_TOTAL_WAGERED_FOR_OUTCOMES'
export const UPDATE_BET_AMOUNT = 'UPDATE_BET_AMOUNT'
export const UPDATE_BET_OUTCOME = 'UPDATE_BET_OUTCOME'
export const UPDATE_CONSTANTS = 'UPDATE_CONSTANTS'
