export const ROUTE_CHANGED = 'router/ROUTE_CHANGED'

// Common
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_STATUS = 'UPDATE_STATUS'

// TimeSafe
export const TIMESAFE_CONSTANTS = 'TIMESAFE_CONSTANTS'
export const TIMESAFE_READONLY = 'TIMESAFE_READONLY'

