export const ROUTE_CHANGED = 'router/ROUTE_CHANGED'

// Common
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_STATUS = 'UPDATE_STATUS'

// TimeSafe
export const TIMESAFE_CONSTANTS = 'TIMESAFE_CONSTANTS'
export const TIMESAFE_READONLY = 'TIMESAFE_READONLY'
export const TIMESAFE_DEPOSIT = 'TIMESAFE_DEPOSIT'
export const TIMESAFE_DEPOSIT_EVENT = 'TIMESAFE_DEPOSIT_EVENT'
export const TIMESAFE_DEPOSIT_AMOUNT = 'TIMESAFE_DEPOSIT_AMOUNT'

